version: '2'
services:
  perl:
    image: ken1flan/perl_test_on_circleci:latest
    ports:
      - "8080:80"
    volumes:
      - .:/code
      - ./app:/var/www
    depends_on:
      - mariadb
    privileged: true
  mariadb:
    image: circleci/mariadb:10.3
