version: 2.1
jobs:
  build:
    docker:
      - image: ken1flan/perl_test_on_circleci:latest

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "cpanfile.snapshot" }}
      - run:
          name: carton install
          command: carton install --deployment
      - save_cache:
          key: dependency-cache-{{ checksum "cpanfile.snapshot" }}
          paths:
            - local

