version: 2.1

executors:
  my-executor:
    docker:
      - image: ken1flan/perl_test_on_circleci:latest
      - image: mariadb:10.3
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: circleci

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "cpanfile.snapshot" }}
      - run:
          name: carton install
          command: carton install --deployment
      - save_cache:
          key: dependency-cache-{{ checksum "cpanfile.snapshot" }}
          paths:
            - local
  test:
    executor: my-executor
    steps:
      - checkout
      - run:
         name: waiting for mariadb to be ready
         command: |
          for i in `seq 10`; do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiging for mariadb to be ready && exit 1
      - run:
         name: set up database
         command: |
          mysql -h localhost -u root circleci < create_tables.sql
          mysql -h localhost -u root circleci -e="SELECT * FROM cats;"
      - run:
         name: test
         command: perl test.pl

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
