version: 2.1
jobs:
  build:
    docker:
      - image: ken1flan/perl_test_on_circleci:latest
      - image: mariadb:10.3
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: circleci
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "cpanfile.snapshot" }}
      - run:
          name: carton install
          command: carton install --deployment
      - save_cache:
          key: dependency-cache-{{ checksum "cpanfile.snapshot" }}
          paths:
            - local
  test:
    docker:
      - image: ken1flan/perl_test_on_circleci:latest
      - image: mariadb:10.3
    steps:
      - checkout
      - run:
         name: test
         command: perl test.pl

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
